-- List each pair of actors that have worked together.
SELECT 
FA1.ACTOR_ID AS ACTOR_ID1,
a1.FIRST_NAME AS ACTOR_FIRST_NAME1,
A1.LAST_NAME AS ACTOR_LAST_NAME1,
FA2.ACTOR_ID AS ACTOR_ID2,
A2.FIRST_NAME AS ACTOR_FIRST_NAME2,
A2.LAST_NAME AS ACTOR_LAST_NAME2
FROM FILM_ACTOR FA1
JOIN FILM_ACTOR FA2 ON FA1.FILM_ID = FA2.FILM_ID AND FA1.ACTOR_ID < FA2.ACTOR_ID
JOIN ACTOR A1 ON FA1.ACTOR_ID = A1.ACTOR_ID
JOIN ACTOR A2 ON FA2.ACTOR_ID = A2.ACTOR_ID
ORDER BY FA1.ACTOR_ID, FA2.ACTOR_ID;

-- For each film, list actor that has acted in more films.
SELECT 
SUB.FILM_ID,
SUB.ACTOR_ID,
A.FIRST_NAME,
A.LAST_NAME,
SUB.FILM_COUNT
FROM (
    SELECT 
        FA.FILM_ID,
        FA.ACTOR_ID,
        COUNT(*) OVER (PARTITION BY FA.FILM_ID ORDER BY COUNT(*) DESC) AS RN,
        COUNT(*) AS FILM_COUNT
    FROM FILM_ACTOR FA
    GROUP BY FA.FILM_ID, FA.ACTOR_ID
    ORDER BY FA.FILM_ID, COUNT(*) DESC
) AS SUB
JOIN ACTOR A ON SUB.ACTOR_ID = A.ACTOR_ID
WHERE SUB.RN = 1;